### ISSUE TITLE
Appropriate license of docker-remove-unused-images

### ISSUE THREAD

**Issue by ffissore** [ffissore/docker-k8s-scripts#1]
@focusaurus I've put your script from [this gist](https://gist.github.com/anildigital/862675ec1b7bccabc311#gistcomment-1626611) into file [docker-remove-unused-images](https://github.com/ffissore/docker-scripts/blob/master/docker-remove-unused-images)

Do you thing you can provide a pull request where you declare your copyright and add a license?

**Comment by focusaurus** [comment]
Sure. Done.

**Comment by ffissore** [comment]
Thank you!
