### ISSUE TITLE
Appropriate license of docker-stop-all

### ISSUE THREAD

**Issue by ffissore** [ffissore/docker-k8s-scripts#2]
@fgrehm I've put your script from [coderwall](https://coderwall.com/p/ewk0mq/stop-remove-all-docker-containers) into file [docker-stop-all](https://github.com/ffissore/docker-scripts/blob/master/docker-stop-all)

Do you thing you can provide a pull request where you declare your copyright and add a license?

**Comment by fgrehm** [comment]
Don't worry about crediting me, its just a simple one liner :dancer: :beers:

**Comment by ffissore** [comment]
Thank you
